name: Azure Python 3.5
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.5.10
    - name: Install Dependencies
      run: |
        make install-azure
    - name: Test with Pylint
      run: | 
        make lint
    - name: Test with Pytest
      run: |
        make test
